name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Hoping you're not using a generator; you can skip build steps
      # - uses: actions/setup-node@v2
      # - run: npm ci
      # - run: npm run build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public' # or whichever folder contains your built site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy pages
        uses: actions/deploy-pages@v4
